### ISSUE TITLE
dashboard/index.yaml missing

### ISSUE THREAD

**Issue by crushallhumans** [duo-labs/isthislegit#2]
Is there a generator script for the GAE Datastore index file?

**Comment by jordan-wright** [comment]
Hey there!

I have no idea how I missed that file when uploading. Looks like it was accidentally left in the `.gitignore` by mistake.

I've uploaded my copy of index.yaml. It's typically auto generated as you use the local dev_appserver.py file and browse around your project.

Let me know if this helps!

**Comment by crushallhumans** [comment]
Works great - thanks much!

**Comment by jordan-wright** [comment]
👍 You bet! I appreciate you being so patient while we work to clean up some inevitable bugs like this one with the initial release.
