### ISSUE TITLE
Minor documentation fix

### ISSUE THREAD

**Issue by kiwiz** [duo-labs/isthislegit#20]
https://github.com/duo-labs/isthislegit/wiki/Installation#creating-the-oauth-client
The oauth block within `manifest.json` should actually be `oauth2`[1], not `oauth`.

1 - https://developer.chrome.com/apps/app_identity#update_manifest

**Comment by jordan-wright** [comment]
Hi @kiwiz!

Thanks for sending this over. You're absolutely right. I've fixed the manifest block in the documentation. Sorry for the trouble!

Thanks again for bringing this to our attention! Let us know if you run into any other issues, as the documentation is still a work in progress.
