### ISSUE TITLE
Running Locally

### ISSUE THREAD

**Issue by arnydo** [duo-labs/isthislegit#28]
First off, this tool looks awesome and would be great to take advantage of.

Is there anything special needed in order to get this running locally without involving GAE?

Thanks.

**Comment by jordan-wright** [comment]
Hey there!

Unfortunately, it will be difficult to get this working outside of GAE. Long term, I'd love to migrate off GAE specific services like NDB, but I'm afraid I have pretty limited time towards active development. There's been a bit of work recently on getting a docker container working, but even it uses the gcloud development server. 🙁 

I'll keep you updated if we get a chance to eventually move this into a locally hosted service! Ideally, I'd love to move it to Flask + Redis + MySQL (or other SQL through SQLAlchemy). Sorry for any inconvenience this causes!

**Comment by arnydo** [comment]
Thanks for the update!

I look forward to the improvements/features to come! Flask, etc. sounds like a great move to make it more versatile depending on the environment.
