### ISSUE TITLE
will not load SSL module

### ISSUE THREAD

**Issue by dystonic** [duo-labs/isthislegit#29]
see this:
https://cloud.google.com/appengine/docs/deprecations/python-ssl-27

I had to add 
libraries:
- name: ssl
  version: latest

to the app.yaml file. 

Please make the change to the root file;  all new deployments will break unless you do (google-side change.)

**Comment by jordan-wright** [comment]
Hi @dystonic,

Thank you for sending this in! I'll see if I can get this tested and added to the app.yaml file ASAP.
