### ISSUE TITLE
Handle /report and /report/

### ISSUE THREAD

**Issue by paddycarver** [duo-labs/isthislegit#43]
Right now the Chrome extension returns an error if the configured URL ends in `/report`, not `/report/`. It took us a moment to figure this out, and it would be a nice bit of polish if either was matched. I'm happy to submit a pull request for this, if you'd like.

**Comment by uBadRequest** [comment]
> Right now the Chrome extension returns an error if the configured URL ends in `/report`, not `/report/`. It took us a moment to figure this out, and it would be a nice bit of polish if either was matched. I'm happy to submit a pull request for this, if you'd like.

Hows this been working for you?
