### ISSUE TITLE
Chrome extension docs out of date

### ISSUE THREAD

**Issue by paddycarver** [duo-labs/isthislegit#44]
Currently the docs for setting up your extension and registering in the chrome webstore seem to be out of date. Notably, [this part](https://github.com/duo-labs/isthislegit/blob/a0cfda92214ed6720ea5de5177cbe481b68a48f1/docs/installation.md#deploying-to-the-webstore) no longer has the visibility options, as far as we can tell.

**Comment by jordan-wright** [comment]
Hey there!

This one was new to me. It looks like it might require [setting up a permission within G Suite](https://support.google.com/chrome/a/answer/2663860?hl=en) for this option to be available. I've added a link to that article in the documentation.

I haven't tried this personally, but will once I get the chance. This _should_ fix the issue but if you don't this working on your side or if my validation doesn't work, we can always re-open this.

Thanks again for mentioning this!
